// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StarTEDSystem.Entities
{
    public partial class Position
    {
        public Position()
        {
            Employees = new HashSet<Employee>();
            InverseReportsToNavigation = new HashSet<Position>();
        }

        public int PositionID { get; set; }
        public string Description { get; set; }
        public int? ReportsTo { get; set; }

        public virtual Position ReportsToNavigation { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Position> InverseReportsToNavigation { get; set; }
    }
}