// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StarTEDSystem.Entities
{
    public partial class Programs
    {
        public Programs()
        {
            Employees = new HashSet<Employee>();
        }

        [Key]

        public int ProgramID { get; set; }

        
        public string ProgramName { get; set; }

       


        public string DiplomaName { get; set; }
        public string SchoolCode { get; set; }
        public decimal Tuition { get; set; }
        public decimal InternationalTuition { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
    }
}